theme: jekyll-theme-architect
title: Technical Scientific paper - ICSE 2022
description: Syntactic Vs Semantic similarity of Artificial and Real Faults in Mutation Testing Studies
show_downloads: true
